import { TILE_SIZE } from './constants';
import type { GameStore, Player } from './types';

const createInitialPlayer = (): Player => ({
    x: TILE_SIZE * 1.5,
    y: TILE_SIZE * 1.5,
    width: TILE_SIZE,
    height: TILE_SIZE * 2,
    hitbox: {
        x: TILE_SIZE * 1.5 + (TILE_SIZE - 60) / 2,
        y: TILE_SIZE * 1.5,
        width: 60,
        height: TILE_SIZE * 2,
    },
    vx: 0,
    vy: 0,
    direction: 1,
    isGrounded: false,
    isApplyingThrust: false,
    isChargingFly: false,
    wantsToFly: false,
    flyChargeTimer: 0,
    shootCooldown: 0,
    animationState: 'stand',
    animationTick: 0,
    currentFrame: 0,
    deathTimer: 0,
    isFrozen: false,
    isFloating: false,
    respawnX: 0,
    respawnY: 0,
    floatWaveTime: 0,
});

export const createInitialStore = (): GameStore => ({
    appState: 'menu',
    gameState: 'start',
    lives: 0,
    score: 0,
    energy: 0,
    energyDecrementRate: 0.1,
    bombsRemaining: 5,
    currentLevelIndex: 0,
    cameraY: 0,
    cameraX: 0,
    isPaused: false,
    levelEndSequence: null,
    levelEndTimer: 0,
    virtualEnergyDrain: null,
    player: createInitialPlayer(),
    walls: [],
    enemies: [],
    lasers: [],
    bombs: [],
    explosions: [],
    miner: null,
    lights: [],
    platforms: [],
    isDark: false,
    explosionFlash: 0,
    fallingEntities: [],
    particles: [],
    floatingScores: [],
    levelDesigns: [],
    levelDataStore: [],
    editorLevel: [],
    selectedTile: '1',
    mouse: { x: 0, y: 0, gridX: 0, gridY: 0, isDown: false },
    keys: {},
    sprites: {},
    joystickManager: null,
    isLaserSticky: false,
    lastShootTap: 0,
    initialLevels: [],
    editorHistory: [],
    editorHistoryIndex: -1,
    dom: {
        canvas: null,
        ctx: null,
        ui: {
            livesCountEl: null,
            scoreCountEl: null,
            energyBarEl: null,
            levelCountEl: null,
            messageOverlay: null,
            messageTitle: null,
            messageText: null,
            gameUiEl: null,
            rightUiEl: null,
            bottomUiEl: null,
            menuBtn: null,
            restartBtn: null,
            menuBtnDesktop: null,
            restartBtnDesktop: null,
            editorPanelEl: null,
            paletteEl: null,
            confirmationModalEl: null,
            notificationModalEl: null,
            notificationTitleEl: null,
            notificationMessageEl: null,
            notificationOkBtn: null,
            exitModalEl: null,
            exitTitleEl: null,
            exitTextEl: null,
            exitConfirmBtn: null,
            exitCancelBtn: null,
            levelSelectorEl: null,
            mobileControlsEl: null,
            joystickZoneEl: null,
            actionZoneEl: null,
            volumeToggle: null,
            startGameBtn: null,
            levelEditorBtn: null,
            playTestBtn: null,
            resumeEditorBtn: null,
            loadLevelBtn: null,
            saveLevelBtn: null,
            generateLevelBtn: null,
            saveAllBtn: null,
            backToMenuBtn: null,
            confirmSaveBtn: null,
            cancelSaveBtn: null,
            undoBtn: null,
            redoBtn: null,
        },
    },
});

