import { TILE_SIZE } from './constants';
import type { GameStore, Player } from './types';

const createInitialPlayer = (): Player => ({
    x: TILE_SIZE * 1.5,
    y: TILE_SIZE * 1.5,
    width: TILE_SIZE,
    height: TILE_SIZE * 2,
    hitbox: {
        x: TILE_SIZE * 1.5 + TILE_SIZE / 4,
        y: TILE_SIZE * 1.5,
        width: TILE_SIZE / 2,
        height: TILE_SIZE * 2,
    },
    vx: 0,
    vy: 0,
    direction: 1,
    isGrounded: false,
    isApplyingThrust: false,
    isChargingFly: false,
    wantsToFly: false,
    flyChargeTimer: 0,
    shootCooldown: 0,
    animationState: 'stand',
    animationTick: 0,
    currentFrame: 0,
    deathTimer: 0,
    isFrozen: false,
});

export const createInitialStore = (): GameStore => ({
    appState: 'menu',
    gameState: 'start',
    lives: 0,
    score: 0,
    energy: 0,
    currentLevelIndex: 0,
    cameraY: 0,
    player: createInitialPlayer(),
    walls: [],
    enemies: [],
    lasers: [],
    bombs: [],
    explosions: [],
    miner: null,
    lights: [],
    isDark: false,
    explosionFlash: 0,
    fallingEntities: [],
    particles: [],
    floatingScores: [],
    levelDesigns: [],
    levelDataStore: [],
    editorLevel: [],
    selectedTile: '1',
    mouse: { x: 0, y: 0, gridX: 0, gridY: 0, isDown: false },
    keys: {},
    sprites: {},
    joystickManager: null,
    initialLevels: [],
    dom: {
        canvas: null,
        ctx: null,
        ui: {
            livesCountEl: null,
            scoreCountEl: null,
            energyBarEl: null,
            levelCountEl: null,
            messageOverlay: null,
            messageTitle: null,
            messageText: null,
            gameUiEl: null,
            editorPanelEl: null,
            paletteEl: null,
            levelDataTextarea: null,
            confirmationModalEl: null,
            levelSelectorEl: null,
            mobileControlsEl: null,
            joystickZoneEl: null,
            actionZoneEl: null,
            startGameBtn: null,
            levelEditorBtn: null,
            playTestBtn: null,
            resumeEditorBtn: null,
            loadLevelBtn: null,
            saveLevelBtn: null,
            exportLevelBtn: null,
            importLevelBtn: null,
            saveAllBtn: null,
            cleanLevelBtn: null,
            backToMenuBtn: null,
            confirmSaveBtn: null,
            cancelSaveBtn: null,
        },
    },
});

